### ISSUE TITLE
Create new project within VSCode platformio

### ISSUE THREAD

**Issue by ruslanin** [darkautism/pio-lgt8fx#2]
Hi,
I have cloned repository into my %USER%.platformio\platforms\
Restart VSCode, but when i try to create new project using LGT8F328P board i have got error
...
Project Configuration File\r\n\n\nError: Could not find the package with 'framework-lgt8fx @ >=1.0.5' requirements for your system 'windows_amd64'"

**Comment by darkautism** [comment]
I notice that platformio v5 uses a different package mechanism. It needs the platform developers to publish their packages first. This platform script is based on v3 and I'm trying to publish these packages.
If you wanna resolve this error before I fix this issue, just download the package and untar it into %User%\.platformio\packages.
https://github.com/darkautism/pio-lgt8fx/releases/tag/1.0.5

**Comment by ruslanin** [comment]
Thank you very much.Project was created and compiled.Very good job. 23.11.2020, 09:55, "kautism" <notifications@github.com>: I notice that platformio v5 uses a different package mechanism. It needs the platform developers to publish their packages first. This platform script is based on v3 and I'm trying to publish these packages.If you wanna resolve this error before I fix this issue, just download the package and untar it into %User%.platformio\packages.https://github.com/darkautism/pio-lgt8fx/releases/tag/1.0.5—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С Уважением,Руслан Иноземцев+7(916) 632 8087

**Comment by darkautism** [comment]
We can install the project from the package manager now.
https://platformio.org/platforms/lgt8f/
