### ISSUE TITLE
LGT8F328P-SSOP20 spi not work

### ISSUE THREAD

**Issue by ghost** [darkautism/pio-lgt8fx#3]
I'm trying to communicate a nrf24 module to the mcu, but it doesn't work. It is probably a pin assignment problem, since this Soc shares pin 8 with 9 and 10 with 11 respectively.

In the arduino ide with version 1.0.6 https://github.com/dbuezas/lgt8fx it works correctly.

**Comment by darkautism** [comment]
Hi jmcastillejo,

Thanks for your report. I publish new version framework-lgt8fx package into platformio's registry and still processing. If you wanna use the latest package before platformio processing you can download newest package from [here](https://github.com/darkautism/pio-lgt8fx/releases/tag/1.0.6) and extract it to your $(platformio installation folder)\packages\framework-lgt8fx folder.

Sincerely,
Kautism
