### ISSUE TITLE
update to v2.0.6

### ISSUE THREAD

**Issue by whyameye** [darkautism/pio-lgt8fx#4]
How might I update this to use v2.0.6 framework? It seems stuck at 1.0.6 which was released back in 2020.

**Comment by FrankBoesing** [comment]
+1

**Comment by FrankBoesing** [comment]
> How might I update this to use v2.0.6 framework? It seems stuck at 1.0.6 which was released back in 2020.

+1

**Comment by darkautism** [comment]
I already published into pio registry and waiting for moderation to been accepted.

Or you can untar this file into `C:\Users\$yourusername\.platformio\packages\framework-lgt8fx`
https://github.com/darkautism/pio-lgt8fx/releases/tag/2.0.6

**Comment by FrankBoesing** [comment]
Thank you! Works so far, but: board_build.f_cpu = 32000000L doesn't seem to work anymore, at least the Serial output is garbage. Any Hint?

**Comment by FrankBoesing** [comment]
Looks like an additional 

```
build_flags =
	-DF_OSC=32000000L
```

is needed.

**Comment by darkautism** [comment]
https://github.com/search?q=repo%3Adbuezas%2Flgt8fx%20f_cpu&type=code
It seems F_CPU define still been using in original repository?

**Comment by darkautism** [comment]
Hi @FrankBoesing 

https://github.com/darkautism/pio-lgt8fx/commit/39d466a28eda46d5c966b023cecd10547520ef72
Could you try add this patch into your json to test it does work or not?

You can find json files in
`C:\Users\<Your User Name>\.platformio\platforms\lgt8fx`

**Comment by FrankBoesing** [comment]
I'm on vacation for a few days, but I can test it at the end of next week.
But the patch looks good - even if I couldn't test it yet.

**Comment by FrankBoesing** [comment]
Hm, no, does not work. 
It is still needed to add -DF_OSC=32000000L to the build_flags. Without, Serial.begin(115200) sends with 57600 (the half speed)

**Comment by darkautism** [comment]
Should been fixed in v1.0.2.
Let me know if it not work.
